[package]
name = "ndless-static-vars"
description = "Rust library for storing static, program-wide parameters for Ndless"
version = "1.0.0"
authors = ["lights0123 <developer@lights0123.com>"]
edition = "2018"
repository = "https://github.com/lights0123/ndless-rs"
license = "MIT OR Apache-2.0"
